INSERT INTO manager VALUES  (1,'Testemail@email.email','test','user');
INSERT INTO manager VALUES  (2,'test@revature.com','REAL_TEST_EMAIL','usery');
INSERT INTO manager VALUES  (3,'test@email.mail','isa','cat');
INSERT INTO batch VALUES(1,'Reston','Sophia','1','Java Full Stack');
INSERT INTO batch VALUES(2,'WVU','Jacob','1','JWA Full Stack');
INSERT INTO associate VALUES (1, 'testemail@email.com', 'testA', 'associate','1A', 1, 1, 2);
INSERT INTO associate VALUES (2, 'testemail@email.com', 'testB', 'associate','1B', 1, 1, 2);
INSERT INTO associate VALUES (3, 'testemail@email.com', 'testC', 'associate','1C', 1, 1, 2);
INSERT INTO associate VALUES (4, 'testemail@email.com', 'testD','associate','1D', 1, 1, 2);
INSERT INTO interview_feedback VALUES  (1,'Great speaker',SYSDATE(),1,1);
INSERT INTO interview_feedback VALUES  (2,'Great programmer',SYSDATE(),2,1);
INSERT INTO interview_feedback VALUES  (3,'Great everything',SYSDATE(),1,2);
INSERT INTO interview_feedback VALUES  (4,'Who hired this guy?',SYSDATE(),2,2);